global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true
      use_sim_time: True
      width: 10
      height: 10
      robot_radius: 0.22
      resolution: 0.05
      track_unknown_space: false
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "mcr_tracking_components::ObstacleLayer"
        enabled: True
        use_tracking_mode: True
        tracking_pose_invisible_radius: 0.8
        tracking_pose_topic: tracking_pose        
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 10.0
          min_obstacle_height: -10.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 6.0
          raytrace_min_range: 0.0
          obstacle_max_range: 5.5
          obstacle_min_range: 0.0
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.55
      always_send_full_costmap: True
  rolling_window_costmap_client:
    ros__parameters:
      use_sim_time: True
  rolling_window_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: True


mcr_planner:
  ros__parameters:
    use_sim_time: True
    planner_name: potential_planner
    potential_planner:
      use_sim_time: True
      plugin: mcr_global_planner/MCRGlobalPlanner
      potential_calculator: mcr_planner_plugins::AStar #Dijkstra
      traceback: mcr_planner_plugins::GradientPath #GridPath    #VonNeumannPath
      publish_potential: false
      print_statistics: false
      neutral_cost: 50
      scale: 3.0
      path_caching: true
      improvement_threshold: -1.0
      use_kernel: true
      unknown_interpretation: lethal

    curve_planner:
      use_sim_time: True
      plugin: mcr_global_planner::MCRCurvePlanner
      curve_type: dubs
      turning_radius: 1.5

    spline_planner:
      use_sim_time: True
      plugin: mcr_global_planner::MCRSplinePlanner
      spline_name: bezier
      pose_topic: "goal_pose1"
      bezier:
        plugin: mcr_planner_plugins::PolynomialFitting
        # plugin: mcr_planner_plugins::BSpliner
        # plugin: mcr_planner_plugins::PolynomialInterpolation
        # plugin: mcr_planner_plugins::BezierSpliner

    grid_base:
      plugin: "astar_planner/AstarPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true
