controller_server:
  ros__parameters:
    use_sim_time: True
    fake_progress_checkerL:
      plugin: "mcr_tracking_components::FakeProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    # DWB parameters
    TrackingTargetL:
      plugin: "dwb_core::DWBLocalPlanner"
      costmap: local_costmap_tracking
      debug_trajectory_details: True
      min_vel_x: -1.5
      min_vel_y: -0.5
      max_vel_x: 1.5
      max_vel_y: 0.5
      max_vel_theta: 1.57
      min_speed_xy: 0.0
      max_speed_xy: 1.5
      min_speed_theta: 0.0
      # Add high threshold velocity for turtlebot 3 issue.
      # https://github.com/ROBOTIS-GIT/turtlebot3_simulations/issues/75
      acc_lim_x: 2.5
      acc_lim_y: 1.0
      acc_lim_theta: 3.2
      decel_lim_x: -2.5
      decel_lim_y: -1.0
      decel_lim_theta: -3.2
      vx_samples: 8
      vy_samples: 5
      vtheta_samples: 8
      sim_time: 0.7
      linear_granularity: 0.05
      angular_granularity: 0.025
      transform_tolerance: 0.2
      xy_goal_tolerance: 0.25
      trans_stopped_velocity: 0.25
      short_circuit_trajectory_evaluation: True
      stateful: True
      critics:
        ["BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      BaseObstacle.scale: 0.02
      PathAlign.scale: 32.0
      PathAlign.forward_point_distance: 0.1
      GoalAlign.scale: 24.0
      GoalAlign.forward_point_distance: 0.1
      PathDist.scale: 32.0
      GoalDist.scale: 24.0
      # RotateToGoal.slowing_factor: 5.0
      RotateToGoal.lookahead_time: -0.4

planner_server:
  ros__parameters:
    SplinePlannerL:
      use_sim_time: True
      plugin: mcr_global_planner/MCRSplinePlanner
      costmap: rolling_window_costmap
      spline_name: linear
      pose_topic: "tracking_pose_in_map"
      # pose_topic: "target_traces"
      linear:
        plugin: mcr_planner_plugins::LinearInterpolation
        # plugin: mcr_planner_plugins::PolynomialFitting
        # plugin: mcr_planner_plugins::BSpliner
        # plugin: mcr_planner_plugins::PolynomialInterpolation
