mcr_bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: map
    robot_base_frame: base_link
    odom_topic: odom_out
    maxwait: 15.0
    target_topic: tracking_pose
    bt_loop_duration: 50
    default_server_timeout: 20
    enable_groot_monitoring: False
    groot_zmq_publisher_port: 1789
    groot_zmq_server_port: 1887
    default_target_tracking_bt_xml: target_tracking.xml
    # 'default_nav_through_poses_bt_xml' and 'default_nav_to_pose_bt_xml' are use defaults:
    # nav2_bt_navigator/navigate_to_pose_w_replanning_and_recovery.xml
    # nav2_bt_navigator/navigate_through_poses_w_replanning_and_recovery.xml
    # They can be set here or via a RewrittenYaml remap from a parent launch file to Nav2.
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_compute_path_spline_poses_action_bt_node
      - nav2_compute_path_through_poses_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_spin_and_search_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_truncate_path_action_bt_node
      - nav2_goal_updater_node_bt_node
      - nav2_tracking_mode_decider_node_bt_node
      - nav2_target_updater_node_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_transform_available_condition_bt_node
      - nav2_time_expired_condition_bt_node
      - nav2_distance_traveled_condition_bt_node
      - nav2_single_trigger_bt_node
      - nav2_exception_verify_bt_node
      - nav2_is_battery_low_condition_bt_node
      - nav2_navigate_through_poses_action_bt_node
      - nav2_navigate_to_pose_action_bt_node
      - nav2_remove_passed_goals_action_bt_node
      - nav2_planner_selector_bt_node
      - nav2_controller_selector_bt_node
      - nav2_goal_checker_selector_bt_node
      - nav2_charger_updater_node_bt_node
      - nav2_change_gait_node_bt_node
      - nav2_seat_adjust_client_node_bt_node
      - nav2_is_battery_in_charge_condition_bt_node

mcr_bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: False

mcr_bt_navigatortracking_target_rclcpp_node:  
  ros__parameters:
    use_sim_time: False
    # TargetUpdaterNode
    global_frame: vodom  
    goal_updater_topic: tracking_pose
    overtime: 1.50
    max_pose_inuse: 0
    dist_throttle: 0.0
    orientation_deriver: mcr_tracking_components::KalmanOrientationDeriver

local_costmap_tracking:
  local_costmap_tracking:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: vodom
      robot_base_frame: base_link
      transform_tolerance: 1.2
      use_sim_time: False
      rolling_window: true
      width: 8
      height: 8
      resolution: 0.05
      footprint: "[[0.35, 0.2], [-0.28, 0.15], [-0.28, -0.15], [0.35, -0.2]]"
      plugins: ["obstacle_layer", "inflation_layer"]
      elevation_layer:
        plugin: "cyberdog_gridmap_costmap_plugin/GridMapCostLayer"
        enabled: True
        min_pass_threshold: -0.15
        max_pass_threshold: 0.15
        topic: elevation_map_raw 
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.35
      range_layer:
        plugin: "nav2_costmap_2d::RangeSensorLayer"
        enabled: True
        topics: ['ultrasonic_payload']
        input_sensor_type: VARIABLE
        phi: 1.2
        inflate_cone: 1.0
        no_readings_timeout: 0.0
        clear_threshold: 0.2
        mark_threshold: 0.8
        clear_on_max_reading: false
      obstacle_layer:
        plugin: "mcr_tracking_components::ObstacleLayer"
        enabled: True
        use_tracking_mode: True 
        tracking_pose_invisible_radius: 0.5
        tracking_pose_topic: tracking_pose
        observation_sources: scan
        scan:
          topic: scan
          max_obstacle_height: 20.0
          min_obstacle_height: -20.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          obstacle_range: 10.0
          raytrace_range: 10.0        
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan
        scan:
          topic: scan
          max_obstacle_height: 20.0
          min_obstacle_height: -20.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 6.0
          raytrace_min_range: 0.0
          obstacle_max_range: 5.5
          obstacle_min_range: 0.0
      static_layer:
        map_subscribe_transient_local: True
      always_send_full_costmap: True
  local_costmap_tracking_client:
    ros__parameters:
      use_sim_time: False
  local_costmap_tracking_rclcpp_node:
    ros__parameters:
      use_sim_time: False

controller_server:
  ros__parameters:
    use_sim_time: False
    odom_topic: odom_out
    controller_frequency: 10.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    progress_checker_plugins: ["fake_progress_checker"]
    goal_checker_plugins: ["xy_goal_checker"] # "precise_goal_checker"
    controller_plugins: ["TrackingTarget"]
    controller_costmaps: ["local_costmap_tracking"]
    fake_progress_checker:
      plugin: "mcr_tracking_components::FakeProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    xy_goal_checker:
      stateful: True
      # plugin: "nav2_controller::SimpleGoalChecker"
      plugin: "mcr_tracking_components::XYGoalChecker"
      xy_goal_tolerance: 0.3
      yaw_goal_tolerance: 0.2
    # DWB parameters
    TrackingTarget:
      plugin: "dwb_core::DWBLocalPlanner"
      costmap: local_costmap_tracking
      debug_trajectory_details: True
      trajectory_generator_name: dwb_plugins::LimitedAccelGenerator  #dwb_plugins::StandardTrajectoryGenerator #
      min_vel_x: 0.0
      min_vel_y: -0.3
      max_vel_x: 1.2
      max_vel_y: 0.3
      max_vel_theta: 1.5
      min_vel_theta: -1.5
      min_speed_xy: 0.0
      max_speed_xy: 1.2
      max_speed_theta: 1.5
      min_speed_theta: -1.5
      acc_lim_x: 1.0
      acc_lim_y: 1.0
      acc_lim_theta: 2.0
      decel_lim_x: -1.0
      decel_lim_y: -1.0
      decel_lim_theta: -2.0
      vx_samples: 8
      vy_samples: 4
      vtheta_samples: 6
      sim_time: 0.9
      linear_granularity: 0.05
      angular_granularity: 0.025
      transform_tolerance: 1.2
      xy_goal_tolerance: 0.25
      trans_stopped_velocity: 0.25
      short_circuit_trajectory_evaluation: True
      stateful: True
      critics: [ "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist", "KeepTargetInsight"]
      BaseObstacle.scale: 20.0
      PathAlign.scale: 32.0
      PathAlign.forward_point_distance: 0.1
      GoalAlign.scale: 24.0
      GoalAlign.forward_point_distance: 0.1
      PathDist.scale: 32.0
      GoalDist.scale: 24.0
      KeepTargetInsight.class: mcr_tracking_components::KeepTargetInsightCritic
      KeepTargetInsight.scale: 26.0
      KeepTargetInsight.target_topic: tracking_pose
      # RotateToGoal.slowing_factor: 5.0
      RotateToGoal.lookahead_time: -0.4

controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

rolling_window_costmap:
  rolling_window_costmap:
    ros__parameters:
      update_frequency: 0.0
      publish_frequency: 1.0
      global_frame: vodom
      robot_base_frame: base_link
      rolling_window: true
      transform_tolerance: 1.2
      use_sim_time: False
      width: 16
      height: 16
      footprint: "[[0.35, 0.2], [-0.28, 0.15], [-0.28, -0.15], [0.35, -0.2]]"
      footprint_padding: 0.05

      resolution: 0.05
      track_unknown_space: false
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "mcr_tracking_components::ObstacleLayer"
        enabled: True
        use_tracking_mode: True
        tracking_pose_invisible_radius: 0.4
        tracking_pose_topic: tracking_pose        
        observation_sources: scan
        scan:
          topic: scan
          max_obstacle_height: 20.0
          min_obstacle_height: -20.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 6.0
          raytrace_min_range: 0.0
          obstacle_max_range: 5.5
          obstacle_min_range: 0.0
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.43
      always_send_full_costmap: True
  rolling_window_costmap_client:
    ros__parameters:
      use_sim_time: False
  rolling_window_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False


planner_server:
  ros__parameters:
    expected_planner_frequency: 5.0
    use_sim_time: False
    planner_plugins: ["SplinePlanner", "PotentialPlanner"]
    planner_costmaps: ["rolling_window_costmap"]
    SplinePlanner:
      use_sim_time: False
      plugin: mcr_global_planner/MCRSplinePlanner
      costmap: rolling_window_costmap
      spline_name: bezier
      pose_topic: "tracking_pose_in_map"
      # pose_topic: "target_traces"
      bezier:
        plugin: mcr_planner_plugins::LinearInterpolation
        # plugin: mcr_planner_plugins::BezierSpliner
        # plugin: mcr_planner_plugins::PolynomialFitting
        # plugin: mcr_planner_plugins::BSpliner
        # plugin: mcr_planner_plugins::PolynomialInterpolation
    PotentialPlanner:
      use_sim_time: False
      plugin: mcr_global_planner/MCRGlobalPlanner
      costmap: rolling_window_costmap
      potential_calculator: mcr_planner_plugins::AStar  #Dijkstra 
      traceback: mcr_planner_plugins::GradientPath #GridPath    #VonNeumannPath  
      publish_potential: false
      print_statistics: false
      neutral_cost: 50
      scale: 3.0
      path_caching: true
      improvement_threshold: -1.0
      use_kernel: true
      unknown_interpretation: lethal    

planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

recoveries_server:
  ros__parameters:
    costmap_topic: local_costmap_tracking/costmap_raw
    footprint_topic: local_costmap_tracking/published_footprint
    cycle_frequency: 10.0
    recovery_plugins: ["spin", "spin_and_search", "backup", "wait"]
    spin:
      plugin: "nav2_recoveries/Spin"
    spin_and_search:
      plugin: "mcr_tracking_components/SpinAndSearch"
    backup:
      plugin: "nav2_recoveries/BackUp"
    wait:
      plugin: "nav2_recoveries/Wait"
    global_frame: vodom
    robot_base_frame: base_link
    transform_timeout: 0.1
    use_sim_time: False
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2
